import { authApi } from "./authApi";

export const {
	useGetProfileQuery,
	// useGetProfileChoicesQuery,
	useLoginMutation,
	// useLogoutMutation,
	useRegisterMutation,
	// useLogoutAllMutation,
	useVerifyEmailMutation,
	useSocialLoginMutation,
	useSocialVerifyLoginMutation,
	useUpdateUserProfileMutation,
	useEditUserProfileMutation,
	useGetUserProfileQuery,
	useGetUserQualificationsQuery,
	useUpdateUserQualificationMutation,
	useGetUserInterestsQuery,
	useUpdateUserInterestsMutation,
	useGetUserResearchAreaQuery,
	useUpdateUserResearchAreaMutation,
	useSendResetPasswordEmailMutation,
	useResetPasswordMutation,
	useEditUserInterestsMutation,
	useEditUserQualificationMutation,
	useEditUserResearchAreaMutation,
	useGetAllUsersQuery,
	useGetAllPublishersProfileQuery,
	// useGetPublisherProfileByIdQuery
	// useEditProfileMutation,
	// useResetPasswordMutation,
	// useChangePasswordMutation,
	// useResetPasswordConfirmMutation,
	// useResendResetPasswordOTPMutation,
	// useResendVerificationCodeMutation,
} = authApi;
