import {
	BookMarked,
	BookText,
	FileSearchIcon,
	Notebook,
	NotebookTextIcon,
	ScrollTextIcon,
} from "lucide-react";

export const NIGERIA_STATES = [
	{ label: "Abia", value: "abia" },
	{ label: "Adamawa", value: "adamawa" },
	{ label: "Akwa Ibom", value: "akwa-ibom" },
	{ label: "Anambra", value: "anambra" },
	{ label: "Bauchi", value: "bauchi" },
	{ label: "Bayelsa", value: "bayelsa" },
	{ label: "Benue", value: "benue" },
	{ label: "Borno", value: "borno" },
	{ label: "Cross River", value: "cross-river" },
	{ label: "Delta", value: "delta" },
	{ label: "Ebonyi", value: "ebonyi" },
	{ label: "Edo", value: "edo" },
	{ label: "Ekiti", value: "ekiti" },
	{ label: "Enugu", value: "enugu" },
	{ label: "Federal Capital Territory", value: "fct" },
	{ label: "Gombe", value: "gombe" },
	{ label: "Imo", value: "imo" },
	{ label: "Jigawa", value: "jigawa" },
	{ label: "Kaduna", value: "kaduna" },
	{ label: "Kano", value: "kano" },
	{ label: "Katsina", value: "katsina" },
	{ label: "Kebbi", value: "kebbi" },
	{ label: "Kogi", value: "kogi" },
	{ label: "Kwara", value: "kwara" },
	{ label: "Lagos", value: "lagos" },
	{ label: "Nasarawa", value: "nasarawa" },
	{ label: "Niger", value: "niger" },
	{ label: "Ogun", value: "ogun" },
	{ label: "Ondo", value: "ondo" },
	{ label: "Osun", value: "osun" },
	{ label: "Oyo", value: "oyo" },
	{ label: "Plateau", value: "plateau" },
	{ label: "Rivers", value: "rivers" },
	{ label: "Sokoto", value: "sokoto" },
	{ label: "Taraba", value: "taraba" },
	{ label: "Yobe", value: "yobe" },
	{ label: "Zamfara", value: "zamfara" },
];

export const roles = [
	{ value: "student", label: "Student" },
	{ value: "research_assistant", label: "Research Assistant" },
	{ value: "graduate_student", label: "Graduate Student" },
	{ value: "phd_student", label: "PhD Student" },
	{ value: "postdoc", label: "Postdoctoral Researcher" },
	{ value: "assistant_professor", label: "Assistant Professor" },
	{ value: "associate_professor", label: "Associate Professor" },
	{ value: "professor", label: "Professor" },
	{ value: "research_scientist", label: "Research Scientist" },
	{ value: "senior_research_scientist", label: "Senior Research Scientist" },
	{ value: "principal_scientist", label: "Principal Scientist" },
	{ value: "lecturer", label: "Lecturer" },
	{ value: "senior_lecturer", label: "Senior Lecturer" },
	{ value: "reader", label: "Reader" },
	{ value: "visiting_professor", label: "Visiting Professor" },
	{ value: "adjunct_professor", label: "Adjunct Professor" },
	{ value: "emeritus_professor", label: "Emeritus Professor" },
	{ value: "department_head", label: "Department Head" },
	{ value: "dean", label: "Dean" },
	{ value: "director", label: "Director" },
	{ value: "manager", label: "Manager" },
	{ value: "consultant", label: "Consultant" },
	{ value: "other", label: "Other" },
];

export const interestTopics = [
	{ value: "climate_change", label: "Climate Change" },
	{ value: "renewable_energy", label: "Renewable Energy" },
	{ value: "sustainable_development", label: "Sustainable Development" },
	{ value: "environmental_science", label: "Environmental Science" },
	{ value: "clean_technology", label: "Clean Technology" },
	{ value: "green_technology", label: "Green Technology" },
	{ value: "carbon_reduction", label: "Carbon Reduction" },
	{ value: "energy_efficiency", label: "Energy Efficiency" },
	{ value: "solar_energy", label: "Solar Energy" },
	{ value: "wind_energy", label: "Wind Energy" },
	{ value: "hydroelectric", label: "Hydroelectric" },
	{ value: "geothermal", label: "Geothermal" },
	{ value: "biomass", label: "Biomass" },
	{ value: "nuclear_energy", label: "Nuclear Energy" },
	{ value: "energy_storage", label: "Energy Storage" },
	{ value: "smart_grid", label: "Smart Grid" },
	{ value: "electric_vehicles", label: "Electric Vehicles" },
	{ value: "sustainable_transport", label: "Sustainable Transport" },
	{ value: "waste_management", label: "Waste Management" },
	{ value: "water_conservation", label: "Water Conservation" },
	{ value: "air_quality", label: "Air Quality" },
	{ value: "biodiversity", label: "Biodiversity" },
	{ value: "conservation", label: "Conservation" },
	{ value: "circular_economy", label: "Circular Economy" },
	{ value: "green_building", label: "Green Building" },
	{ value: "sustainable_agriculture", label: "Sustainable Agriculture" },
	{ value: "food_security", label: "Food Security" },
	{ value: "ocean_conservation", label: "Ocean Conservation" },
	{ value: "marine_biology", label: "Marine Biology" },
	{ value: "forest_conservation", label: "Forest Conservation" },
	{ value: "urban_sustainability", label: "Urban Sustainability" },
	{ value: "policy_analysis", label: "Policy Analysis" },
	{ value: "environmental_law", label: "Environmental Law" },
	{ value: "climate_policy", label: "Climate Policy" },
	{ value: "environmental_economics", label: "Environmental Economics" },
	{ value: "sustainability_metrics", label: "Sustainability Metrics" },
	{ value: "life_cycle_assessment", label: "Life Cycle Assessment" },
	{ value: "carbon_footprint", label: "Carbon Footprint" },
	{ value: "environmental_monitoring", label: "Environmental Monitoring" },
	{ value: "remote_sensing", label: "Remote Sensing" },
	{ value: "gis_applications", label: "GIS Applications" },
	{ value: "data_analytics", label: "Data Analytics" },
	{ value: "machine_learning", label: "Machine Learning" },
	{ value: "artificial_intelligence", label: "Artificial Intelligence" },
	{ value: "iot_applications", label: "IoT Applications" },
	{ value: "blockchain", label: "Blockchain" },
	{ value: "other", label: "Other" },
];

export const publicationTypeOptions = [
	{
		value: "research",
		label: "Research",
		icon: BookText,
		color: "bg-[#D1FADF] text-[#039855]",
	},
	{
		value: "report",
		label: "Report",
		icon: BookMarked,
		color: "bg-[#D1E9FF] text-[#0086C9]",
	},
	{
		value: "case_study",
		label: "Case Study",
		icon: NotebookTextIcon,
		color: "bg-[#F4F3FF] text-[#6927DA]",
	},
	{
		value: "industry_insight",
		label: "Industry Insight",
		icon: Notebook,
		color: "bg-[#F4F3FF] text-[#6927DA]",
	},
	{
		value: "policy",
		label: "Policy",
		icon: FileSearchIcon,
		color: "bg-[#D1E9FF] text-[#0086C9]",
	}
	
];

export const tagColor = [
	
]

export const badgeColors = [
  "bg-[#F6EDE1] text-[#7C5A2C]",
  "bg-[#E1F6ED] text-[#2C7C55]",
  "bg-[#E1E9F6] text-[#2C447C]",
  "bg-[#F6E1EC] text-[#7C2C5A]",
  "bg-[#F6F3E1] text-[#7C6B2C]",
]
